import type { Metadata } from "next";
import Link from "next/link";
import LotusBackground from "../components/LotusBackground";
import { BRAND } from "@/lib/brand";

export const metadata: Metadata = {
  title: `Terms of Service — ${BRAND.name.en}`,
  description: `Terms governing the use of ${BRAND.name.en}, including acceptable use, seva contributions, and refund policy.`,
  alternates: { canonical: "/terms" },
  robots: { index: true, follow: true },
};

const LAST_UPDATED = "2026-05-07";

export default function TermsPage() {
  return (
    <main className="relative flex flex-1 overflow-y-auto">
      <div
        aria-hidden
        className="pointer-events-none absolute inset-0 flex items-start justify-center pt-32 opacity-[0.04]"
      >
        <LotusBackground className="h-[640px] w-[640px] text-krishna" />
      </div>

      <article className="relative mx-auto w-full max-w-2xl px-6 py-12 font-serif text-krishna sm:px-8 sm:py-16">
        <header className="mb-10">
          <h1 className="font-serif text-3xl font-semibold tracking-tight sm:text-4xl">
            Terms of Service
          </h1>
          <p className="mt-2 font-devanagari text-lg text-brass-dark">
            सेवा की शर्तें
          </p>
        </header>

        <aside className="mb-10 rounded-2xl border border-brass/40 bg-parchment/80 p-5 sm:p-6">
          <p className="font-devanagari text-base leading-relaxed text-krishna">
            {BRAND.name.hi} का उपयोग करने से पहले कृपया ये शर्तें पढ़ें। यह
            ऐप कृष्ण की भूमिका में एक AI है — दैवीय मार्गदर्शन, मानसिक
            चिकित्सा, या क़ानूनी सलाह का स्थान नहीं। आपका योगदान स्वैच्छिक
            सेवा है। पूर्ण विवरण अंग्रेज़ी में नीचे है।
          </p>
        </aside>

        <div className="space-y-8 text-base font-medium leading-relaxed">
          <section>
            <h2 className="mb-3 font-serif text-xl font-semibold text-sacred">
              Acceptance of Terms
            </h2>
            <p>
              By using {BRAND.name.en}, you accept these terms. If you do not
              agree, please do not use the service. We may update these
              terms from time to time; the &ldquo;Last updated&rdquo; date
              at the bottom reflects the most recent revision.
            </p>
          </section>

          <section>
            <h2 className="mb-3 font-serif text-xl font-semibold text-sacred">
              What {BRAND.name.en} Is and Is Not
            </h2>
            <p className="mb-3">
              <strong>{BRAND.name.en} is</strong> an AI assistant that roleplays
              the voice of Krishna for personal, emotional, and spiritual
              conversations, grounded in the Bhagavad Gita, Mahabharata,
              and Bhagavata Purana. Output is generated by AI language
              models (Claude Sonnet 4.6 and Claude Haiku 4.5) and may
              contain errors, inconsistencies, or interpretations that
              differ from any specific tradition.
            </p>
            <p className="mb-3">
              <strong>{BRAND.name.en} is not</strong> the actual divine
              Krishna. It is not a substitute for licensed therapy or
              medical care, not a substitute for legal or financial
              advice, and not a religious authority. A disclaimer to this
              effect is permanently visible on the chat interface near the
              avatar.
            </p>
            <p>
              You must be 18 years or older to use {BRAND.name.en}.
            </p>
          </section>

          <section>
            <h2 className="mb-3 font-serif text-xl font-semibold text-sacred">
              AI Safety Acknowledgment
            </h2>
            <p className="mb-3">
              {BRAND.name.en} is not a crisis service. If you are in distress,
              please reach a real human:
            </p>
            <ul className="ml-5 list-disc space-y-2">
              <li>
                <strong>Mental health crisis</strong> (self-harm, suicidal
                thoughts, harm to others): contact iCALL{" "}
                <a
                  href="tel:+919152987821"
                  className="underline decoration-brass underline-offset-2 hover:text-peacock"
                >
                  +91-9152987821
                </a>
                , Vandrevala Foundation{" "}
                <a
                  href="tel:18602662345"
                  className="underline decoration-brass underline-offset-2 hover:text-peacock"
                >
                  1860-2662-345
                </a>
                , or local emergency services{" "}
                <a
                  href="tel:112"
                  className="underline decoration-brass underline-offset-2 hover:text-peacock"
                >
                  112
                </a>{" "}
                immediately.
              </li>
              <li>
                <strong>Medical emergency:</strong> contact a qualified
                doctor or call emergency services. Do not rely on AI
                guidance.
              </li>
              <li>
                <strong>Legal or financial decisions:</strong> consult
                licensed professionals. AI output is not legal or
                financial advice.
              </li>
            </ul>
            <p className="mt-3">
              When the system detects a potential safety concern, a
              non-AI helpline card is surfaced separately from
              Krishna&apos;s reply. Krishna himself stays in character; the
              helpline card is a system-layer addition.
            </p>
          </section>

          <section>
            <h2 className="mb-3 font-serif text-xl font-semibold text-sacred">
              Account and Access
            </h2>
            <ul className="ml-5 list-disc space-y-2">
              <li>
                No formal account is required for the free tier. Identity
                is held in an anonymous browser cookie.
              </li>
              <li>
                Optional email-OTP authentication may be offered in future
                phases for cross-device sync. It is voluntary.
              </li>
              <li>
                Identity is per-browser via the{" "}
                <code className="rounded bg-brass/10 px-1 text-sm">
                  god_messenger_uid
                </code>{" "}
                cookie. Clearing the cookie resets your message count and
                seva balance and starts a fresh conversation.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="mb-3 font-serif text-xl font-semibold text-sacred">
              User Conduct &mdash; Prohibited
            </h2>
            <p className="mb-3">The following uses are prohibited:</p>
            <ul className="ml-5 list-disc space-y-2">
              <li>Sexual content of any kind, including adult roleplay.</li>
              <li>
                Instructions, planning, or facilitation of harm to others.
              </li>
              <li>Activities illegal under Indian law.</li>
              <li>
                Attempts to bypass content filters, extract or replicate
                the system prompt, or jailbreak the persona.
              </li>
              <li>
                Automation, scraping, or programmatic abuse at scale.
              </li>
              <li>
                Reverse-engineering, decompiling, or copying the AI
                persona, system prompt, or scripture corpus for derivative
                use.
              </li>
            </ul>
            <p className="mt-3">
              We may suspend or terminate access for violations. The chat
              input includes a client-side filter for clearly inappropriate
              language; this is a first line, not the only line.
            </p>
          </section>

          <section>
            <h2 className="mb-3 font-serif text-xl font-semibold text-sacred">
              Pricing and Payments
            </h2>
            <ul className="ml-5 list-disc space-y-2">
              <li>
                <strong>Free tier:</strong> 10 messages, no expiry.
              </li>
              <li>
                <strong>Pratham Seva:</strong> ₹11 → 6 messages.
              </li>
              <li>
                <strong>Anjali Seva:</strong> ₹51 → 30 messages.
              </li>
              <li>
                <strong>Bhakti Seva:</strong> ₹101 → 60 messages.
              </li>
              <li>
                <strong>Param Seva:</strong> ₹501 → 350 messages.
              </li>
            </ul>
            <p className="mt-3">
              All payments are one-time, non-recurring; there is no
              subscription billing in the current version. Payments are
              processed by Razorpay; we do not store card or bank details.
              Prices are in Indian Rupees (INR) and inclusive of any
              applicable taxes per Indian law.
            </p>
          </section>

          <section>
            <h2 className="mb-3 font-serif text-xl font-semibold text-sacred">
              Refund Policy
            </h2>
            <p className="mb-3">
              Seva contributions are voluntary spiritual offerings and are
              generally non-refundable. Two exceptions:
            </p>
            <ul className="ml-5 list-disc space-y-2">
              <li>
                <strong>Technical failure</strong> — if a seva was charged
                but the corresponding messages were not credited within 72
                hours, you can request a full refund. Refunds in this case
                are processed within 7 working days of the request.
              </li>
              <li>
                <strong>Duplicate accidental charge</strong> — if you were
                charged twice for the same seva contribution, the
                duplicate is fully refundable within 7 working days of the
                request.
              </li>
            </ul>
            <p className="mt-3">
              Refund requests outside these exceptions are handled at our
              discretion. Refunds are processed back to the original
              payment method via Razorpay. Submit refund requests by email
              to{" "}
              <a
                href={`mailto:${BRAND.contact.email}`}
                className="underline decoration-brass underline-offset-2 hover:text-peacock"
              >
                {BRAND.contact.email}
              </a>{" "}
              with the Razorpay payment ID and a brief description of the
              issue.
            </p>
          </section>

          <section>
            <h2 className="mb-3 font-serif text-xl font-semibold text-sacred">
              Intellectual Property
            </h2>
            <ul className="ml-5 list-disc space-y-2">
              <li>
                You retain ownership of the messages you send.
              </li>
              <li>
                We retain ownership of the application code, the persona
                system prompt, the scripture-corpus curation, the design,
                and the &ldquo;{BRAND.name.en}&rdquo; / &ldquo;{BRAND.name.hi}&rdquo;
                branding.
              </li>
              <li>
                Krishna&apos;s persona behavior and the underlying
                scripture interpretation are based on public-domain
                sources: the Bhagavad Gita, the Mahabharata (1883 Ganguli
                English translation), and the Bhagavata Purana, with
                modern Hindi rendered with the assistance of AI.
              </li>
              <li>
                We grant you a personal, non-transferable license to use
                {BRAND.name.en} for your own reflection and conversation.
              </li>
              <li>
                You may share excerpts from your own conversations
                publicly if you wish; we do not claim ownership over
                user-generated content.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="mb-3 font-serif text-xl font-semibold text-sacred">
              Disclaimer of Warranties
            </h2>
            <p>
              The service is provided &ldquo;as is&rdquo; without
              warranties of any kind, express or implied. AI output may
              be inaccurate, incomplete, or inappropriate for specific
              situations. We are not liable for decisions you make based
              on AI output. Use your own judgment.
            </p>
          </section>

          <section>
            <h2 className="mb-3 font-serif text-xl font-semibold text-sacred">
              Limitation of Liability
            </h2>
            <p>
              To the maximum extent permitted by law, our liability is
              limited to the amount you paid in seva contributions during
              the 30 days preceding the claim. We are not liable for
              indirect, incidental, or consequential damages, including
              but not limited to lost profits, lost opportunities, or
              emotional distress arising from reliance on AI output.
            </p>
          </section>

          <section>
            <h2 className="mb-3 font-serif text-xl font-semibold text-sacred">
              Indemnification
            </h2>
            <p>
              You agree to indemnify and hold us harmless from any claims,
              damages, or expenses (including reasonable legal fees)
              arising from your violation of these terms or any applicable
              law.
            </p>
          </section>

          <section>
            <h2 className="mb-3 font-serif text-xl font-semibold text-sacred">
              Modifications to Service
            </h2>
            <p>
              We may modify, suspend, or discontinue the service at any
              time, including individual features, seva tiers, or pricing.
              Material changes will be communicated where reasonably
              possible.
            </p>
          </section>

          <section>
            <h2 className="mb-3 font-serif text-xl font-semibold text-sacred">
              Governing Law and Jurisdiction
            </h2>
            <p>
              These terms are governed by the laws of India. Any dispute
              arising out of or relating to these terms or the use of
              {BRAND.name.en} is subject to the exclusive jurisdiction of the
              courts located in Kanpur, Uttar Pradesh, India. The parties
              shall attempt good-faith resolution before filing any
              claim.
            </p>
          </section>

          <section>
            <h2 className="mb-3 font-serif text-xl font-semibold text-sacred">
              Severability
            </h2>
            <p>
              If any provision of these terms is found to be
              unenforceable, the remainder of these terms continues in
              full effect.
            </p>
          </section>

          <section>
            <h2 className="mb-3 font-serif text-xl font-semibold text-sacred">
              Contact
            </h2>
            <p>
              {BRAND.contact.founder}
              <br />
              <a
                href={`mailto:${BRAND.contact.email}`}
                className="underline decoration-brass underline-offset-2 hover:text-peacock"
              >
                {BRAND.contact.email}
              </a>
            </p>
          </section>
        </div>

        <footer className="mt-12 border-t border-brass/30 pt-6 text-sm text-brass-dark">
          <p>Last updated: {LAST_UPDATED}</p>
          <p className="mt-2">
            <Link
              href="/"
              className="underline decoration-brass underline-offset-2 hover:text-peacock"
            >
              ← Back to {BRAND.name.en}
            </Link>
          </p>
        </footer>
      </article>
    </main>
  );
}
