import type { Metadata } from "next";
import Link from "next/link";
import LotusMandala from "../components/motifs/LotusMandala";

export const metadata: Metadata = {
  title: "Privacy Policy — Divya Vani",
  description:
    "How Divya Vani collects, uses, and protects your data. Notice issued under India's Digital Personal Data Protection Act 2023.",
  alternates: { canonical: "/privacy" },
  robots: { index: true, follow: true },
};

const LAST_UPDATED = "2026-05-07";

export default function PrivacyPage() {
  return (
    <main className="relative flex flex-1 overflow-y-auto">
      <div
        aria-hidden
        className="pointer-events-none absolute inset-0 flex items-start justify-center pt-32 opacity-[0.04]"
      >
        <LotusMandala className="h-[640px] w-[640px] text-krishna" />
      </div>

      <article className="relative mx-auto w-full max-w-2xl px-6 py-12 font-serif text-krishna sm:px-8 sm:py-16">
        <header className="mb-10">
          <h1 className="font-serif text-3xl font-semibold tracking-tight sm:text-4xl">
            Privacy Policy
          </h1>
          <p className="mt-2 font-devanagari text-lg text-brass-dark">
            गोपनीयता नीति
          </p>
        </header>

        <aside className="mb-10 rounded-2xl border border-brass/40 bg-parchment/80 p-5 sm:p-6">
          <p className="font-devanagari text-base leading-relaxed text-krishna">
            दिव्य वाणी में आपकी निजता का सम्मान किया जाता है। यह पृष्ठ बताता
            है कि हम कौन-सी जानकारी एकत्र करते हैं, क्यों, और आपके अधिकार
            क्या हैं। पूर्ण विवरण अंग्रेज़ी में नीचे पढ़ें। किसी भी प्रश्न
            के लिए नीचे दिए गए ईमेल पर हमसे संपर्क करें।
          </p>
        </aside>

        <div className="space-y-8 text-base font-medium leading-relaxed">
          <section>
            <h2 className="mb-3 font-serif text-xl font-semibold text-sacred">
              About Divya Vani
            </h2>
            <p>
              Divya Vani is an AI service that roleplays the character of
              Krishna from the Bhagavad Gita, Mahabharata, and Bhagavata
              Purana. Krishna&apos;s voice in this app is generated by an AI
              language model (Anthropic&apos;s Claude). Divya Vani is{" "}
              <strong>not</strong> divine guidance, not a substitute for
              licensed therapy, medical care, or professional legal or
              financial advice. A disclaimer to this effect is permanently
              visible on the chat interface.
            </p>
          </section>

          <section>
            <h2 className="mb-3 font-serif text-xl font-semibold text-sacred">
              Data We Collect
            </h2>
            <ul className="ml-5 list-disc space-y-2">
              <li>
                <strong>Anonymous identifier.</strong> An HttpOnly cookie
                named{" "}
                <code className="rounded bg-brass/10 px-1 text-sm">
                  god_messenger_uid
                </code>{" "}
                containing a randomly generated UUID. One-year expiry,
                per-browser, not accessible to client-side JavaScript.
              </li>
              <li>
                <strong>Optional name.</strong> If you choose to share your
                name during a conversation, it is stored so Krishna can
                address you in future replies. This is voluntary; the
                conversation works without it.
              </li>
              <li>
                <strong>Conversation memory (not verbatim log).</strong>{" "}
                Messages you send are processed by Anthropic Claude (Sonnet
                4.6 + Haiku 4.5) to generate Krishna&apos;s responses. We
                do <strong>not</strong> store a verbatim record of every
                message. We do store a brief AI-generated summary of your
                emotional thread (current concern, current emotion, running
                summary across turns) so subsequent conversations have
                continuity.
              </li>
              <li>
                <strong>Payment metadata.</strong> When you make a seva
                contribution, we store the Razorpay order ID, payment ID,
                amount in paise, tier (Pratham / Anjali / Bhakti / Param),
                status, and timestamps. We do <strong>not</strong> store
                bank details, card numbers, or UPI IDs — Razorpay handles
                those directly between your device and their servers.
              </li>
              <li>
                <strong>Webhook event metadata.</strong> Razorpay payment
                webhooks (event ID, event type, full event payload from
                Razorpay) are stored for audit and idempotency. The payload
                contains payment status and method (e.g., netbanking) but
                never card or bank-account numbers.
              </li>
              <li>
                <strong>Anonymous analytics.</strong> Aggregate page-view
                counts via Vercel Web Analytics. No individual IPs are
                stored or linked to identifiers.
              </li>
              <li>
                <strong>Error reports.</strong> If a server-side error
                occurs, the stack trace and error context are sent to
                Sentry for debugging. Personal information (IPs, request
                headers, cookies) is explicitly suppressed (
                <code className="rounded bg-brass/10 px-1 text-sm">
                  sendDefaultPii: false
                </code>
                ).
              </li>
            </ul>
          </section>

          <section>
            <h2 className="mb-3 font-serif text-xl font-semibold text-sacred">
              Data We Do Not Collect
            </h2>
            <ul className="ml-5 list-disc space-y-2">
              <li>
                We do not see or store your bank details, card numbers, or
                UPI IDs. These flow directly between your device and
                Razorpay.
              </li>
              <li>We do not track you across other websites.</li>
              <li>
                We do not sell or rent data to advertisers, data brokers,
                or any third party.
              </li>
              <li>We do not run advertising networks.</li>
              <li>
                Our error tracker (Sentry) is configured to <em>not</em>{" "}
                receive your IP address, request headers, or cookies.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="mb-3 font-serif text-xl font-semibold text-sacred">
              Third-Party Services
            </h2>
            <p className="mb-3">
              We use the following processors to deliver Divya Vani. Each
              has its own privacy policy, linked below.
            </p>
            <ul className="ml-5 list-disc space-y-3">
              <li>
                <strong>Anthropic (USA)</strong> — generates Krishna&apos;s
                responses (Claude Sonnet 4.6, Claude Haiku 4.5). Receives
                your current message plus relevant scripture context. Per
                Anthropic&apos;s Commercial Terms, your data is not used
                to train Anthropic&apos;s models. Privacy:{" "}
                <a
                  href="https://www.anthropic.com/legal/privacy"
                  target="_blank"
                  rel="noreferrer"
                  className="underline decoration-brass underline-offset-2 hover:text-peacock"
                >
                  anthropic.com/legal/privacy
                </a>
                .
              </li>
              <li>
                <strong>Google (USA)</strong> — generates text embeddings
                (Gemini) used to retrieve relevant scripture for each
                message. Receives the message text. Privacy:{" "}
                <a
                  href="https://policies.google.com/privacy"
                  target="_blank"
                  rel="noreferrer"
                  className="underline decoration-brass underline-offset-2 hover:text-peacock"
                >
                  policies.google.com/privacy
                </a>
                .
              </li>
              <li>
                <strong>Supabase</strong> — stores the data described above
                in a managed Postgres database. Service-role access from
                our server only. Privacy:{" "}
                <a
                  href="https://supabase.com/privacy"
                  target="_blank"
                  rel="noreferrer"
                  className="underline decoration-brass underline-offset-2 hover:text-peacock"
                >
                  supabase.com/privacy
                </a>
                .
              </li>
              <li>
                <strong>Razorpay (India)</strong> — processes payments.
                Receives your payment intent and bank, card, or UPI
                details directly from your device; we never see those
                details. Privacy:{" "}
                <a
                  href="https://razorpay.com/privacy/"
                  target="_blank"
                  rel="noreferrer"
                  className="underline decoration-brass underline-offset-2 hover:text-peacock"
                >
                  razorpay.com/privacy
                </a>
                .
              </li>
              <li>
                <strong>Vercel (USA)</strong> — hosts the application;
                serves pages and runs serverless API functions. Privacy:{" "}
                <a
                  href="https://vercel.com/legal/privacy-policy"
                  target="_blank"
                  rel="noreferrer"
                  className="underline decoration-brass underline-offset-2 hover:text-peacock"
                >
                  vercel.com/legal/privacy-policy
                </a>
                .
              </li>
              <li>
                <strong>Sentry (USA)</strong> — error tracking. Configured
                with{" "}
                <code className="rounded bg-brass/10 px-1 text-sm">
                  sendDefaultPii: false
                </code>{" "}
                so personal request data is not transmitted. Privacy:{" "}
                <a
                  href="https://sentry.io/privacy/"
                  target="_blank"
                  rel="noreferrer"
                  className="underline decoration-brass underline-offset-2 hover:text-peacock"
                >
                  sentry.io/privacy
                </a>
                .
              </li>
            </ul>
          </section>

          <section>
            <h2 className="mb-3 font-serif text-xl font-semibold text-sacred">
              Cross-Border Data Transfer
            </h2>
            <p>
              Some of our processors (Anthropic, Google, Vercel, Sentry)
              are based outside India. Under Section 16 of the Digital
              Personal Data Protection Act 2023, cross-border transfer is
              permitted subject to government-notified restrictions. As of
              the effective date of this notice, no such restrictions
              apply to these jurisdictions. We will update this notice if
              the regulations change.
            </p>
          </section>

          <section>
            <h2 className="mb-3 font-serif text-xl font-semibold text-sacred">
              Your Rights
            </h2>
            <p className="mb-3">
              Under India&apos;s Digital Personal Data Protection Act
              2023, you have the following rights:
            </p>
            <ul className="ml-5 list-disc space-y-2">
              <li>
                <strong>Right to access:</strong> request a summary of the
                data we hold about you.
              </li>
              <li>
                <strong>Right to correction and erasure:</strong> request
                that we correct inaccurate data or delete your data.
              </li>
              <li>
                <strong>Right to grievance redressal:</strong> raise
                concerns about how your data is handled.
              </li>
              <li>
                <strong>Right to nominate:</strong> appoint someone to
                exercise these rights on your behalf in the event of
                incapacity or death.
              </li>
            </ul>
            <p className="mt-3">
              To exercise any of these rights, email us at{" "}
              <a
                href="mailto:krishnayadav123345@gmail.com"
                className="underline decoration-brass underline-offset-2 hover:text-peacock"
              >
                krishnayadav123345@gmail.com
              </a>
              . We respond within 30 days as required by Section 13 of the
              DPDP Act.
            </p>
          </section>

          <section>
            <h2 className="mb-3 font-serif text-xl font-semibold text-sacred">
              Children&apos;s Data
            </h2>
            <p>
              Divya Vani is not intended for users under 18 years of age.
              We do not knowingly collect data from minors. If we learn
              that data from a minor has been collected, we will delete it
              promptly. Parents or guardians who believe their child has
              used the service can contact us for deletion.
            </p>
          </section>

          <section>
            <h2 className="mb-3 font-serif text-xl font-semibold text-sacred">
              Data Retention
            </h2>
            <ul className="ml-5 list-disc space-y-2">
              <li>
                <strong>Memory data</strong> (extracted summaries, name,
                preferences): retained while your account is active.
                Deletion requests honored within 30 days.
              </li>
              <li>
                <strong>Payment records:</strong> retained for 7 years per
                the Income Tax Act and standard Indian accounting
                requirements.
              </li>
              <li>
                <strong>Anonymous cookies:</strong> 1-year expiry; can be
                cleared via your browser at any time.
              </li>
              <li>
                <strong>Sentry error logs:</strong> 30-day retention
                (Sentry&apos;s default).
              </li>
            </ul>
          </section>

          <section>
            <h2 className="mb-3 font-serif text-xl font-semibold text-sacred">
              Security
            </h2>
            <ul className="ml-5 list-disc space-y-2">
              <li>All data in transit is encrypted via HTTPS (TLS).</li>
              <li>
                The identity cookie is HttpOnly — not accessible to
                client-side JavaScript, mitigating cross-site scripting
                risk.
              </li>
              <li>
                API keys for Anthropic, Google, Razorpay, and the Supabase
                service-role are server-only; they are never exposed to
                browsers.
              </li>
              <li>
                Razorpay webhook deliveries are validated using HMAC-SHA256
                signatures before being processed.
              </li>
              <li>
                No security claim is absolute. No system can guarantee
                complete protection against determined adversaries.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="mb-3 font-serif text-xl font-semibold text-sacred">
              Changes to This Policy
            </h2>
            <p>
              We may update this notice. Material changes will be reflected
              on this page with a revised &ldquo;Last updated&rdquo; date.
              Continued use of Divya Vani after such changes constitutes
              acceptance of the revised policy.
            </p>
          </section>

          <section>
            <h2 className="mb-3 font-serif text-xl font-semibold text-sacred">
              Contact and Grievance Officer
            </h2>
            <p>
              For privacy questions, deletion requests, or grievances under
              the DPDP Act:
            </p>
            <p className="mt-3">
              Krishna Yadav
              <br />
              <a
                href="mailto:krishnayadav123345@gmail.com"
                className="underline decoration-brass underline-offset-2 hover:text-peacock"
              >
                krishnayadav123345@gmail.com
              </a>
            </p>
            <p className="mt-3">
              Per Section 13 of the DPDP Act, we acknowledge grievances and
              respond within 30 days.
            </p>
          </section>
        </div>

        <footer className="mt-12 border-t border-brass/30 pt-6 text-sm text-brass-dark">
          <p>Last updated: {LAST_UPDATED}</p>
          <p className="mt-2">
            <Link
              href="/"
              className="underline decoration-brass underline-offset-2 hover:text-peacock"
            >
              ← Back to Divya Vani
            </Link>
          </p>
        </footer>
      </article>
    </main>
  );
}
