import type { Metadata } from "next";
import Link from "next/link";
import Atmosphere from "../components/Atmosphere";
import BackToChat from "../components/BackToChat";
import PolicySummary from "../components/PolicySummary";
import { BRAND } from "@/lib/brand";
import { absoluteUrl, jsonLdScript, RSS_ALTERNATE } from "@/lib/seo";

export const metadata: Metadata = {
  title: `Privacy Policy — ${BRAND.name.en}`,
  description: `How ${BRAND.name.en} collects, uses, and protects your data. Notice issued under India's Digital Personal Data Protection Act 2023.`,
  alternates: { canonical: "/privacy", types: RSS_ALTERNATE },
  openGraph: {
    url: absoluteUrl("/privacy"),
    title: `Privacy Policy | ${BRAND.name.en}`,
    description: `How ${BRAND.name.en} collects, uses, and protects your data. Notice issued under India's Digital Personal Data Protection Act 2023.`,
  },
  twitter: {
    card: "summary_large_image",
    title: `Privacy Policy | ${BRAND.name.en}`,
    description: `How ${BRAND.name.en} collects, uses, and protects your data.`,
  },
  robots: { index: true, follow: true },
};

const LAST_UPDATED = "2026-05-15";

export default function PrivacyPage() {
  const privacyJsonLd = {
    "@context": "https://schema.org",
    "@type": "WebPage",
    name: `Privacy Policy | ${BRAND.name.en}`,
    url: absoluteUrl("/privacy"),
    description: `How ${BRAND.name.en} collects, uses, and protects your data.`,
    dateModified: LAST_UPDATED,
    isPartOf: {
      "@type": "WebSite",
      name: BRAND.name.en,
      url: BRAND.url,
    },
  };

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={jsonLdScript(privacyJsonLd)}
      />
      <main className="dv-scroll relative flex-1 overflow-y-auto overflow-x-hidden">
        <Atmosphere mode="distant" intensity={0.6} vignette={1} />

      <article className="relative z-10 mx-auto w-full max-w-[1100px] px-6 py-12 font-[family-name:var(--font-serif)] text-ink sm:px-10 sm:py-16">
        <BackToChat />

        <PolicySummary lastUpdated={LAST_UPDATED} />

        <div
          id="full-policy"
          className="mx-auto max-w-2xl scroll-mt-20 space-y-8 text-base font-medium leading-relaxed text-ink"
        >
          <section>
            <h2 className="mb-3 font-[family-name:var(--font-display)] text-2xl font-normal text-gold">
              About {BRAND.name.en}
            </h2>
            <p>
              {BRAND.name.en} is an AI service that roleplays the character
              of Krishna from the Bhagavad Gita, Mahabharata, and Bhagavata
              Purana. Krishna&apos;s voice in this app is generated by an AI
              language model (Anthropic&apos;s Claude). {BRAND.name.en} is{" "}
              <strong>not</strong> divine guidance, not a substitute for
              licensed therapy, medical care, or professional legal or
              financial advice. A disclaimer to this effect is permanently
              visible on the chat interface.
            </p>
          </section>

          <section>
            <h2 className="mb-3 font-[family-name:var(--font-display)] text-2xl font-normal text-gold">
              Data We Collect
            </h2>
            <ul className="ml-5 list-disc space-y-2">
              <li>
                <strong>Anonymous browser identifier.</strong> An HttpOnly
                cookie named{" "}
                <code className="rounded bg-brass/10 px-1 text-sm">
                  god_messenger_uid
                </code>{" "}
                containing a randomly generated UUID. One-year expiry,
                per-browser, not accessible to client-side JavaScript.
                This is how we recognize you across visits without an
                account.
              </li>
              <li>
                <strong>Account name.</strong> When you choose to share
                your name during a conversation, it is stored so Krishna
                can address you in future replies. This is voluntary;
                the conversation works without it.
              </li>
              <li>
                <strong>Conversation summary.</strong> A brief AI-generated
                summary of your emotional thread across turns — the
                current concern, the current emotion, and a running
                narrative — stored so Krishna can continue the
                conversation across sessions instead of starting fresh
                each time. Field name:{" "}
                <code className="rounded bg-brass/10 px-1 text-sm">
                  users_memory.context_summary
                </code>
                .
              </li>
              <li>
                <strong>Long-term theme of your conversations.</strong> A
                short phrase capturing the slow-moving theme across many
                turns — used silently to shape the tone and the verse
                selection Krishna reaches for. Never narrated back to
                you. Field name:{" "}
                <code className="rounded bg-brass/10 px-1 text-sm">
                  users_memory.growing_edge
                </code>
                .
              </li>
              <li>
                <strong>Message count.</strong> A simple integer used to
                track how many messages you have sent toward the free
                tier (10 messages) before a seva contribution is asked.
              </li>
              <li>
                <strong>Seva purchase records.</strong> When you make a
                seva contribution, we store the Razorpay order ID,
                payment ID, amount in paise, tier (Pratham / Anjali /
                Bhakti / Param), status, and timestamps — used for
                refund handling and financial-compliance audit. We do{" "}
                <strong>not</strong> store bank details, card numbers,
                or UPI IDs — Razorpay handles those directly between
                your device and their servers.
              </li>
              <li>
                <strong>Full conversation logs.</strong> Verbatim user
                messages and Krishna&apos;s replies are stored in the
                table{" "}
                <code className="rounded bg-brass/10 px-1 text-sm">
                  chat_logs
                </code>{" "}
                so we can review them for product improvement (see{" "}
                <em>Human review of conversations</em> below). These
                logs are automatically deleted after 180 days. You can
                opt out of this logging at any time via{" "}
                <Link
                  href="/settings"
                  className="underline decoration-brass underline-offset-2 hover:text-peacock"
                >
                  /settings
                </Link>
                ; when you opt out, future conversations are not logged
                in this table at all.
              </li>
              <li>
                <strong>Voice audio.</strong> When you use the
                microphone on the chat input, short utterance chunks
                of the recorded audio are sent to Sarvam AI (Saaras
                V3 — an Indian speech-to-text service based in
                Bengaluru; data does <strong>not</strong> leave India)
                for transcription. Each audio chunk is immediately
                discarded server-side after its transcription text is
                produced — only the resulting text becomes part of
                your conversation. We do <strong>not</strong> retain
                audio files.
              </li>
              <li>
                <strong>Krishna&apos;s voice (text-to-speech).</strong>{" "}
                <span className="italic">
                  To play Krishna&apos;s voice, the reply text is sent to
                  ElevenLabs (a US-based company) so the audio can be
                  generated. This data may be stored in the United States.
                  We use this service only to generate audio; the text sent
                  is not used by ElevenLabs to train their models.
                </span>
                <span className="mt-2 block font-[family-name:var(--font-devanagari)] not-italic leading-[1.7]">
                  कृष्ण की आवाज़ सुनने के लिए, उनका जवाब-पाठ ElevenLabs (एक
                  अमेरिकी कंपनी) के सर्वरों पर भेजा जाता है ताकि वहाँ ध्वनि
                  बनाई जा सके। यह डेटा अमेरिका में संग्रहीत हो सकता है। हम इस
                  सेवा का उपयोग केवल आवाज़ बनाने के लिए करते हैं, और भेजा गया
                  पाठ ElevenLabs द्वारा अपने मॉडल को प्रशिक्षित करने के लिए
                  उपयोग नहीं किया जाता।
                </span>
              </li>
              <li>
                <strong>Local chat history.</strong> To keep your
                conversation visible if you refresh the page or return
                later, the messages shown in your chat are stored in
                your browser&apos;s localStorage. This data stays on
                your device only — it is <strong>not</strong> sent to
                our servers, <strong>not</strong> synced across devices,
                and is automatically removed when you clear your
                browser data.
              </li>
              <li>
                <strong>Webhook event metadata.</strong> Razorpay payment
                webhooks (event ID, event type, full event payload from
                Razorpay) are stored for audit and idempotency. The
                payload contains payment status and method (e.g.,
                netbanking) but never card or bank-account numbers.
              </li>
              <li>
                <strong>Anonymous analytics.</strong> Aggregate page-view
                counts via Vercel Web Analytics. No individual IPs are
                stored or linked to identifiers.
              </li>
              <li>
                <strong>Error reports.</strong> If a server-side error
                occurs, the stack trace and error context are sent to
                Sentry for debugging. Personal information (IPs, request
                headers, cookies) is explicitly suppressed (
                <code className="rounded bg-brass/10 px-1 text-sm">
                  sendDefaultPii: false
                </code>
                ).
              </li>
            </ul>
          </section>

          <section>
            <h2 className="mb-3 font-[family-name:var(--font-display)] text-2xl font-normal text-gold">
              Human Review of Conversations
            </h2>
            <p className="mb-3">
              {BRAND.name.en} is built by a solo founder. To improve
              Krishna&apos;s voice — to catch when a reply lands wrong,
              to learn where the persona drifts, to make the next
              user&apos;s experience better — the founder occasionally
              reviews conversation logs. This is human review for product
              improvement, not automated training of an AI model. The
              same approach is used by Google Gemini, OpenAI
              ChatGPT, and Pi by Inflection, who also disclose human
              review in their privacy policies.
            </p>
            <p className="mb-3">
              You can disable this review for your future conversations
              at any time via{" "}
              <Link
                href="/settings"
                className="underline decoration-brass underline-offset-2 hover:text-peacock"
              >
                /settings
              </Link>
              . When disabled, your future conversations are not logged
              in our{" "}
              <code className="rounded bg-brass/10 px-1 text-sm">
                chat_logs
              </code>{" "}
              table at all. The conversation summary (
              <code className="rounded bg-brass/10 px-1 text-sm">
                context_summary
              </code>
              ) is still saved because Krishna needs it to remember the
              thread across sessions — this is product function, not
              review material.
            </p>
            <p>
              Existing conversations logged before you opted out remain
              until they are auto-purged at 180 days, or until you
              delete your data via{" "}
              <Link
                href="/settings"
                className="underline decoration-brass underline-offset-2 hover:text-peacock"
              >
                /settings
              </Link>
              .
            </p>
          </section>

          <section>
            <h2 className="mb-3 font-[family-name:var(--font-display)] text-2xl font-normal text-gold">
              Data We Do Not Collect
            </h2>
            <ul className="ml-5 list-disc space-y-2">
              <li>
                We do not see or store your bank details, card numbers, or
                UPI IDs. These flow directly between your device and
                Razorpay.
              </li>
              <li>We do not track you across other websites.</li>
              <li>
                We do not sell or rent data to advertisers, data brokers,
                or any third party.
              </li>
              <li>We do not run advertising networks.</li>
              <li>
                Our error tracker (Sentry) is configured to <em>not</em>{" "}
                receive your IP address, request headers, or cookies.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="mb-3 font-[family-name:var(--font-display)] text-2xl font-normal text-gold">
              Third-Party Services
            </h2>
            <p className="mb-3">
              We use the following processors to deliver {BRAND.name.en}. Each
              has its own privacy policy, linked below.
            </p>
            <ul className="ml-5 list-disc space-y-3">
              <li>
                <strong>Anthropic (USA)</strong> — generates Krishna&apos;s
                responses (Claude Sonnet 4.6, Claude Haiku 4.5). Receives
                your current message plus relevant scripture context. Per
                Anthropic&apos;s Commercial Terms, your data is not used
                to train Anthropic&apos;s models. Privacy:{" "}
                <a
                  href="https://www.anthropic.com/legal/privacy"
                  target="_blank"
                  rel="noreferrer"
                  className="underline decoration-brass underline-offset-2 hover:text-peacock"
                >
                  anthropic.com/legal/privacy
                </a>
                .
              </li>
              <li>
                <strong>Google (USA)</strong> — generates text embeddings
                (Gemini) used to retrieve relevant scripture for each
                message. Receives the message text. Privacy:{" "}
                <a
                  href="https://policies.google.com/privacy"
                  target="_blank"
                  rel="noreferrer"
                  className="underline decoration-brass underline-offset-2 hover:text-peacock"
                >
                  policies.google.com/privacy
                </a>
                .
              </li>
              <li>
                <strong>ElevenLabs (USA)</strong> — generates Krishna&apos;s
                spoken voice (text-to-speech). Receives the reply text to be
                voiced. Per ElevenLabs&apos; terms, text submitted via the
                API is not used to train their models. Privacy:{" "}
                <a
                  href="https://elevenlabs.io/privacy"
                  target="_blank"
                  rel="noreferrer"
                  className="underline decoration-brass underline-offset-2 hover:text-peacock"
                >
                  elevenlabs.io/privacy
                </a>
                .
              </li>
              <li>
                <strong>Supabase</strong> — stores the data described above
                in a managed Postgres database. Service-role access from
                our server only. Privacy:{" "}
                <a
                  href="https://supabase.com/privacy"
                  target="_blank"
                  rel="noreferrer"
                  className="underline decoration-brass underline-offset-2 hover:text-peacock"
                >
                  supabase.com/privacy
                </a>
                .
              </li>
              <li>
                <strong>Razorpay (India)</strong> — processes payments.
                Receives your payment intent and bank, card, or UPI
                details directly from your device; we never see those
                details. Privacy:{" "}
                <a
                  href="https://razorpay.com/privacy/"
                  target="_blank"
                  rel="noreferrer"
                  className="underline decoration-brass underline-offset-2 hover:text-peacock"
                >
                  razorpay.com/privacy
                </a>
                .
              </li>
              <li>
                <strong>Vercel (USA)</strong> — hosts the application;
                serves pages and runs serverless API functions. Privacy:{" "}
                <a
                  href="https://vercel.com/legal/privacy-policy"
                  target="_blank"
                  rel="noreferrer"
                  className="underline decoration-brass underline-offset-2 hover:text-peacock"
                >
                  vercel.com/legal/privacy-policy
                </a>
                .
              </li>
              <li>
                <strong>Sentry (USA)</strong> — error tracking. Configured
                with{" "}
                <code className="rounded bg-brass/10 px-1 text-sm">
                  sendDefaultPii: false
                </code>{" "}
                so personal request data is not transmitted. Privacy:{" "}
                <a
                  href="https://sentry.io/privacy/"
                  target="_blank"
                  rel="noreferrer"
                  className="underline decoration-brass underline-offset-2 hover:text-peacock"
                >
                  sentry.io/privacy
                </a>
                .
              </li>
              <li>
                <strong>Plausible Analytics (EU)</strong> —
                privacy-friendly website analytics: no cookies, no
                cross-site tracking, no personal identifiers. Used to
                understand aggregate funnel and traffic patterns.
                GDPR / DPDP / CCPA compliant by default. Hosted by
                Plausible Insights OÜ (Estonia, EU). Privacy:{" "}
                <a
                  href="https://plausible.io/privacy"
                  target="_blank"
                  rel="noreferrer"
                  className="underline decoration-brass underline-offset-2 hover:text-peacock"
                >
                  plausible.io/privacy
                </a>
                .
              </li>
            </ul>
          </section>

          <section>
            <h2 className="mb-3 font-[family-name:var(--font-display)] text-2xl font-normal text-gold">
              Cross-Border Data Transfer
            </h2>
            <p>
              Some of our processors (Anthropic, Google, ElevenLabs,
              Vercel, Sentry, Plausible) are based outside India. Under
              Section 16 of the Digital
              Personal Data Protection Act 2023, cross-border transfer is
              permitted subject to government-notified restrictions. As of
              the effective date of this notice, no such restrictions
              apply to these jurisdictions. We will update this notice if
              the regulations change.
            </p>
          </section>

          <section>
            <h2 className="mb-3 font-[family-name:var(--font-display)] text-2xl font-normal text-gold">
              Your Rights
            </h2>
            <p className="mb-3">
              Under India&apos;s Digital Personal Data Protection Act
              2023, you have the following rights:
            </p>
            <ul className="ml-5 list-disc space-y-2">
              <li>
                <strong>Right to access:</strong> request a summary of the
                data we hold about you.
              </li>
              <li>
                <strong>Right to correction and erasure:</strong> request
                that we correct inaccurate data or delete your data.
              </li>
              <li>
                <strong>Right to grievance redressal:</strong> raise
                concerns about how your data is handled.
              </li>
              <li>
                <strong>Right to nominate:</strong> appoint someone to
                exercise these rights on your behalf in the event of
                incapacity or death.
              </li>
            </ul>
            <p className="mt-3">
              To exercise any of these rights, email us at{" "}
              <a
                href={`mailto:${BRAND.contact.email}`}
                className="underline decoration-brass underline-offset-2 hover:text-peacock"
              >
                {BRAND.contact.email}
              </a>
              . We respond within 30 days as required by Section 13 of the
              DPDP Act.
            </p>

            <ul className="mt-5 ml-5 list-disc space-y-2">
              <li>
                <strong>Opt out of conversation review</strong> — toggle
                in{" "}
                <Link
                  href="/settings"
                  className="underline decoration-brass underline-offset-2 hover:text-peacock"
                >
                  /settings
                </Link>
                . Takes effect immediately for future conversations.
              </li>
              <li>
                <strong>Delete all your data</strong> — &ldquo;Delete
                everything&rdquo; button in{" "}
                <Link
                  href="/settings"
                  className="underline decoration-brass underline-offset-2 hover:text-peacock"
                >
                  /settings
                </Link>
                . Removes conversation logs, safety events, summary,
                name, and memory. Payment records are retained per
                Indian financial law.
              </li>
              <li>
                <strong>View this policy</strong> — you&apos;re reading
                it now.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="mb-3 font-[family-name:var(--font-display)] text-2xl font-normal text-gold">
              Children&apos;s Data
            </h2>
            <p>
              {BRAND.name.en} is not intended for users under 18 years of age.
              We do not knowingly collect data from minors. If we learn
              that data from a minor has been collected, we will delete it
              promptly. Parents or guardians who believe their child has
              used the service can contact us for deletion.
            </p>
          </section>

          <section>
            <h2 className="mb-3 font-[family-name:var(--font-display)] text-2xl font-normal text-gold">
              Data Retention
            </h2>
            <ul className="ml-5 list-disc space-y-2">
              <li>
                <strong>Conversation logs (chat_logs):</strong> 180 days,
                then automatically deleted by a nightly purge. Skipped
                entirely for users who have opted out of conversation
                review via{" "}
                <Link
                  href="/settings"
                  className="underline decoration-brass underline-offset-2 hover:text-peacock"
                >
                  /settings
                </Link>
                .
              </li>
              <li>
                <strong>Conversation summary, name, and memory
                (users_memory):</strong> retained until you delete your
                data via{" "}
                <Link
                  href="/settings"
                  className="underline decoration-brass underline-offset-2 hover:text-peacock"
                >
                  /settings
                </Link>
                . If you continue using {BRAND.name.en} indefinitely,
                this data persists indefinitely so Krishna can continue
                to remember the thread of your conversations.
              </li>
              <li>
                <strong>Safety events</strong> (flagged turns only,
                stored in the{" "}
                <code className="rounded bg-brass/10 px-1 text-sm">
                  safety_events
                </code>{" "}
                table): retained for safety review and pattern detection,
                no fixed automatic-deletion window. These are reviewed
                under the duty-of-care described in our Terms.
              </li>
              <li>
                <strong>Payment records:</strong> retained per Indian
                financial law (typically 7+ years per the Income Tax Act
                and RBI reconciliation requirements). NOT deleted when
                you delete your data via{" "}
                <Link
                  href="/settings"
                  className="underline decoration-brass underline-offset-2 hover:text-peacock"
                >
                  /settings
                </Link>
                .
              </li>
              <li>
                <strong>Voice audio:</strong> never retained.
                Transcribed via Sarvam AI Saaras V3 (Bengaluru, India
                — data stays in India) and immediately discarded
                server-side after the transcription text is produced.
              </li>
              <li>
                <strong>Webhook event audit:</strong> retained for
                Razorpay reconciliation and idempotency. No user-facing
                impact; not deleted when you delete your data.
              </li>
              <li>
                <strong>Anonymous cookies:</strong> 1-year expiry; can be
                cleared via your browser at any time. Cleared
                automatically when you use the &ldquo;Delete all my
                data&rdquo; button in{" "}
                <Link
                  href="/settings"
                  className="underline decoration-brass underline-offset-2 hover:text-peacock"
                >
                  /settings
                </Link>
                .
              </li>
              <li>
                <strong>Sentry error logs:</strong> 30-day retention
                (Sentry&apos;s default). No personal information is sent
                to Sentry (see <em>Data We Collect</em> above).
              </li>
            </ul>
          </section>

          <section>
            <h2 className="mb-3 font-[family-name:var(--font-display)] text-2xl font-normal text-gold">
              Security
            </h2>
            <ul className="ml-5 list-disc space-y-2">
              <li>All data in transit is encrypted via HTTPS (TLS).</li>
              <li>
                The identity cookie is HttpOnly — not accessible to
                client-side JavaScript, mitigating cross-site scripting
                risk.
              </li>
              <li>
                API keys for Anthropic, Google, Razorpay, and the Supabase
                service-role are server-only; they are never exposed to
                browsers.
              </li>
              <li>
                Razorpay webhook deliveries are validated using HMAC-SHA256
                signatures before being processed.
              </li>
              <li>
                No security claim is absolute. No system can guarantee
                complete protection against determined adversaries.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="mb-3 font-[family-name:var(--font-display)] text-2xl font-normal text-gold">
              Changes to This Policy
            </h2>
            <p>
              We may update this notice. Material changes will be reflected
              on this page with a revised &ldquo;Last updated&rdquo; date.
              Continued use of {BRAND.name.en} after such changes constitutes
              acceptance of the revised policy.
            </p>
          </section>

          <section>
            <h2 className="mb-3 font-[family-name:var(--font-display)] text-2xl font-normal text-gold">
              Contact and Grievance Officer
            </h2>
            <p>
              For privacy questions, deletion requests, or grievances under
              the DPDP Act:
            </p>
            <p className="mt-3">
              {BRAND.contact.founder}
              <br />
              <a
                href={`mailto:${BRAND.contact.email}`}
                className="underline decoration-brass underline-offset-2 hover:text-peacock"
              >
                {BRAND.contact.email}
              </a>
            </p>
            <p className="mt-3">
              Per Section 13 of the DPDP Act, we acknowledge grievances and
              respond within 30 days.
            </p>
          </section>
        </div>

        <footer className="mt-12 border-t border-brass/30 pt-6 text-sm text-brass-dark">
          <p>Last updated: {LAST_UPDATED}</p>
          <p className="mt-2">
            <Link
              href="/"
              className="underline decoration-brass underline-offset-2 hover:text-peacock"
            >
              ← Back to {BRAND.name.en}
            </Link>
          </p>
        </footer>
      </article>
      </main>
    </>
  );
}
